### ISSUE TITLE
Select A CI/CD Provider

### ISSUE THREAD

**Issue by kurron** [Violet-Sloth/Project-Violet-Sloth#17]
[Travis CI](https://github.com/marketplace/travis-ci) and [Circle CI](https://github.com/marketplace/circleci) look like good choices to handle our continuous integration and continuous delivery needs.  We need to pick one.

**Comment by fromcj** [comment]
My vote goes to TravisCI. I was initially leaning towards CircleCI but it seems to support a very limited selection of OSes, and Travis seems to be widely adopted so it can't be all that bad.

**Comment by kurron** [comment]
@fromcj I don't suppose you could whip up a short comparison for us?  This could either be written or in verbal form.  Whatever we chose should go into the Decision Log of the guide book so we don't forget why we selected one over the other.

**Comment by mcmcgonagle** [comment]
I'm writing up a comment for Serverless framework but if you read this page it recommend using some of the capability it provides as your CI/CD provider: https://serverless.com/framework/docs/providers/aws/guide/deploying/

**Comment by sarahmau** [comment]
I agree with @fromcj to pick Travis CI. According to https://hackernoon.com/continuous-integration-circleci-vs-travis-ci-vs-jenkins-41a1c2bd95f5

> > Travis CI and CircleCI are almost the same
> Both of them:
> Have YAML file as a config
> Are cloud-based
> Have support of Docker to run tests
> What does TravisCI offer that CircleCI doesn’t?
> Option to run tests on Linux and Mac OS X at same time
> Supports more languages out of the box:
> Android, C, C#, C++, Clojure, Crystal, D, Dart, Erlang, Elixir, F#, Go, Groovy, Haskell, Haxe, Java, JavaScript (with Node.js), Julia, Objective-C, Perl, Perl6, PHP, Python, R, Ruby, Rust, Scala, Smalltalk, Visual Basic
> Support of build matrix
> Build matrix is a tool that gives an opportunity to run tests with different versions of language and packages. You may customize it in different ways. For example, fails of some environments can trigger notifications but don’t fail all the build ( that’s helpful for development versions of packages)

Travis CI also appears to be more popular and offers tutorials for different languages. https://stackshare.io/stackups/circleci-vs-codeship-vs-travis-ci#more

**Comment by kurron** [comment]
@fromcj I dedicated some of my "nerd time" this weekend to reading the Travis docs and I see that they support [publishing to Lambda](https://docs.travis-ci.com/user/deployment/lambda/), which could be super useful to us.

**Comment by kurron** [comment]
@fromcj It also appears to have [HipChat integration](https://docs.travis-ci.com/user/notifications/#Configuring-HipChat-notifications), so we can all know when a build breaks!

**Comment by kurron** [comment]
The [Atom](https://docs.travis-ci.com/user/build-feeds/) and [desktop](https://docs.travis-ci.com/user/cc-menu/) notifications are also very interesting.

**Comment by sarahmau** [comment]
@kurron Do we want to settle on Travis CI for now for our testing? It seems both easy to get started with, and has so many things we can add.

**Comment by sarahmau** [comment]
Linting integration for sure! Here is a sublime and atom one :) 

https://github.com/sabhiram/sublime-travis-yml-lint Sublime 
https://github.com/mschuchard/linter-travis-lint

**Comment by kurron** [comment]
@sarahmau I think that decision needs to made as a team so we'll probably want to wait for @fromcj  notes but I can say I liked what I've seen in the documentation enough to rig up one of my personal Groovy/Docker projects to see how it fairs.  I still don't know how secrets are kept out of the Travis descriptor, though, which is super important.

**Comment by fromcj** [comment]
So here's a quick and dirty rundown to cover the most important points (to me at least)

Travis and CIrcle are, at the most base level, more or less identical. That means with Travis we get a cloud based service with a documented REST API and Web UI that supports Docker and is easy to set up and get running. That covers our most basic needs for this project.

The biggest advantage Travis provides us actually isn't the build matrix (though that is cool) but simply it supports more operating systems that Circle. 

As to @kurron's question of how to handle secrets in Travis, it seems that they have a fairly intuitive system in place to handle them documented here: https://docs.travis-ci.com/user/encryption-keys/

To me, I think Travis will cover every use case we have for this project. That plus the fact that it is widely recommended and thus heavily documented not just in its own docs and forums but other places on the internet like StackOverflow make it at least, if not a clear choice, a fully serviceable one for us.

**Comment by fromcj** [comment]
If anyone has questions about this, feel free to leave them here and we can meet and go over anything yet to be covered or answered
