### ISSUE TITLE
Evaluate The Serverless Framework

### ISSUE THREAD

**Issue by kurron** [Violet-Sloth/Project-Violet-Sloth#20]
One of us should look into [Serveless](https://serverless.com/)'s Python support and see if we want to use it to help with the Lambda portion of the solution.

**Comment by mcmcgonagle** [comment]
I can take a look at the documentation and mess around with it.

**Comment by mcmcgonagle** [comment]
I started to evaluate Serverless framework and decided to compare it against another option I like from AWS called Chalice. 

| Feature | Serverless | Chalice |
|--------|------------------|---------|
| Type  |  Full Framework | Microframework |
| Providers | AWS, Google Cloud, Azure & more | AWS Only |
| Language Support for Function | NodeJS, Python,Java, & more | Python Only |
| CLI | Node.js based | Python based |
|CLI Description|It manages your code as well as your infrastructure|A command line tool for creating, deploying, and managing your app| 
| Resource Management | Yes- Severless.yaml/ Cloudformation through CLI | Cloudformation (SAM template)-You package it yourself and deploy outside of Chalice CLI. |
| Concept | Services (organizational unit/project file) comprised of Resources (infrastructure), Events (AWS events such as API GW HTTP Request) and Functions (code that does a job). Defined in YAML/JSON file. | Similar to building a Python Flask app- CLI magic handles deployment.  |
|CI/CD Provider| Yes, built in to CLI.  | Yes, through other AWS Toolsets: http://chalice.readthedocs.io/en/latest/topics/cd.html |
| Local Testing | Yes, through CLI. | Yes, through CLI |
Plugins | Yes., community created. https://github.com/serverless/plugins | Build your own/Python Libraries |

**Comment by mcmcgonagle** [comment]
Zappa is also another option that could be used: https://www.zappa.io/ 
This basically converts a Flask app into serverless one.

**Comment by kurron** [comment]
I'm not sure what is more important, @mcmcgonagle , getting out of the gate quickly or something more long term.  Now that I'm typing this, I think getting started quickly makes sense.  If the project succeeds and is still fun for us, we can always repackage the code as needed.

**Comment by mcmcgonagle** [comment]
@kurron I think Serverless can be just as fast however, it looks like it is a little more complex to learn. I think both options are viable and useful to learn. I'm going to try and read more about them this weekend.

**Comment by mcmcgonagle** [comment]
I think the consensus was this would be useful if the project becomes larger. For the initial scope it seemed to be a little bit of overkill.
